Module 3 Capstone Project
Oklukeok/financial-metrics-app pull request #4
Opened 2022-12-02 19:34 UTC by Oklukeok

Features:
-App created with React and Redux
-Consuming API information
-Tests with Jest
-Responsive Design

2022-12-02 19:52 UTC, zieeco requested changes
Hi @Oklukeok ,


Great job so far! 👏 
You've done it well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 19:52 UTC, zieeco commented on README.md
- Please, let's give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/) to make our readme more professional.

2022-12-02 19:52 UTC, zieeco commented on README.md
### TESTS

- Your tests are not passing. Please, let's try fixing this issue.


![Screenshot from 2022-12-02 20-44-09](https://user-images.githubusercontent.com/59397159/205374591-60f37df9-3b09-47b4-8b1e-adcc98b93f61.png)

2022-12-02 23:50 UTC, Oklukeok commented
Testing Fixed
![image](https://user-images.githubusercontent.com/93407216/205410286-48177572-cdee-4de5-bf07-4fb3f160d498.png)

2022-12-03 00:11 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Lucas, 
## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
README is professional. :heavy_check_mark:
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-03 01:51 UTC, merged